### ISSUE TITLE
Empty recommended quest list for certain items

### ISSUE THREAD

**Issue by chkee** [Expugn/priconne-quest-helper#23]
**Describe the bug**
Empty recommended quest list for certain items.
It only happens to `copper, silver, gold, purple, and misc` tier.
`Common` tier works fine.

**To Reproduce**
1. Go to https://expugn.github.io/priconne-quest-helper/
2. Expand any of `Copper/Silver/Gold/Purple/Misc.` section.
3. Increase any item of said section to 1.
4. Scroll down and see the empty `Recommended Quests`.

**Expected behavior**
List of quests for the selected item.

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Chrome: Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by Expugn** [comment]
Seems to be fixed now on my devices. Thanks for the report.
