### ISSUE TITLE
Can't select the rei(new year) with the legacy equipment data

### ISSUE THREAD

**Issue by lyjjrs** [Expugn/priconne-quest-helper#24]
**Describe the bug**
Can't select the rei(new year) with the legacy equipment data
same for yui(new year) and hiyori(new year)

**To Reproduce**
1. Change language to korean
2. Go to the Settings tab
3. Change Equipment Data Type to Legacy Equipment Data (Before 2019.08.31) (KR)
4. Save Settings (Optional)
5. Go to the Presets tab
6. Select the rei(new year)
7. See result

**Screenshots**
1. ![image](https://user-images.githubusercontent.com/48942435/78005969-4d18e100-7377-11ea-9ffb-0b63fd83d7b7.png)
2. ![image](https://user-images.githubusercontent.com/48942435/78006040-6588fb80-7377-11ea-8786-f8bd4e9c42a4.png)
3. ![image](https://user-images.githubusercontent.com/48942435/78006087-79ccf880-7377-11ea-81e4-bf1dc72199b1.png)

**Comment by Expugn** [comment]
The issue should be fixed now, thanks for the report
