### ISSUE TITLE
Feature: add an input to enter exact number of item in inventory.

### ISSUE THREAD

**Issue by Akenaide** [Expugn/priconne-quest-helper#31]
Hello, thanks for your great work.

**Is your feature request related to a problem? Please describe.**

The inventory feature is really great and i'd like to point something. 

When I'm grinding I update the items in the inventory, if it's a new item the quick increment are enough (thoses [https://i.imgur.com/wiQB9Ej.png](https://i.imgur.com/wiQB9Ej.png)) but if it's an "old" item and I discover that I have a bunch I need to open the inventory search the right item and update.

I found this process tiring after few runs.

**Describe the solution you'd like**

I think adding a input in the same pop up than the quick increment will improve this use case.

**Describe alternatives you've considered**

Maybe using replace instead of increment when you use the add item page in the inventory will be enough so people can update their items without checking and updating if they have it or adding if not.

**Comment by Expugn** [comment]
I will consider adding an input on the pop up, thank you for the suggestion.
Another alternative you should consider is that clicking the item you want to edit in your inventory list lets you edit the amount you have, as shown in the image below if you didn't know that.
![Capture](https://user-images.githubusercontent.com/5342885/84059891-2a570a00-a970-11ea-867c-9155d6cb925b.PNG)

**Comment by Akenaide** [comment]
Thanks you.

Yes, I'm aware. This is what I meant when I said "I need to open the inventory search the right item and update." 

I don't think it's enough because you need to open and search in the inventory when it would be easier to update in the quest list (and the quick increment is a good idea) and the items's order in the inventory is not always the same as in game (eg when you add a previously out of stock item it will be shown at the end).

**Comment by Expugn** [comment]
Your suggested feature has been added here: <https://github.com/Expugn/priconne-quest-helper/commit/ae21a357fda579a17fd45df422313a3b04dc3b20>

To open the input, you can click on your current inventory amount (or anywhere that's the dark transparent rectangle).
After making changes to the input, you can press the `OK` button or your `ENTER` key (while the input is selected) to make your changes.
![Capture](https://user-images.githubusercontent.com/5342885/84252621-b0379a00-aac3-11ea-8021-be21c4149510.PNG)

**Comment by Akenaide** [comment]
Thanks you o/
