### ISSUE TITLE
Accurate relative input for the inline inventory editor

### ISSUE THREAD

**Issue by koma-cute** [Expugn/priconne-quest-helper#33]
**Is your feature request related to a problem? Please describe.**
After running a stage and viewing the overall output of items dropped, I used the inline inventory editor's number input field as implemented in #31. Since I was matching up the items I got with the field input, and the +/- buttons are near it, I assumed the number input field was also relative input, rather than absolute, which resulted in inaccurately recording the item drops I got and reruns of unnecessary stages.

**Describe the solution you'd like**
An option to make the number input box add items relative to the current inventory count.

**Describe alternatives you've considered**
More +/- buttons with more smaller numbers for granular control over the number of items. Perhaps the design could be something like `-X  -5  -1    100    +1  +5  +X`, with X being the craft amount and 100 being the current count.

**Comment by Expugn** [comment]
I'll keep this in mind, thanks for the suggestion

**Comment by Expugn** [comment]
Went with your alternative suggestion and added more +/- buttons into the inline inventory editor.
Couldn't really think of a good way to fit two inputs for relative/absolute amounts without it being confusing, so hopefully this solution is fine.
Sorry about the delay too, lol.

**Comment by koma-cute** [comment]
My original idea was that there would be a checkbox in the settings which changed the behavior of the main textbox, but I guess that's kind of obscure. This works too, so no problem! Thanks for the update.
