### ISSUE TITLE
Option to View remaining required ingredients based on inventory

### ISSUE THREAD

**Issue by Notoriouzb** [Expugn/priconne-quest-helper#35]
Is it possible to add an option that changes the way the required ingredients number is show? I'd like to see the total ingredients minus what is on my inventory right now so I can quickly assess how many of each ingredient I still need to farm.

This is useful when making decisions of what stage to farm for how long, when multiple stages drop an ingredient and you still need 80 of it for example, you can decide to farm it together with others even if it is in a lower drop chance.

**Comment by Expugn** [comment]
Your suggestion should be active, thank you!
