### ISSUE TITLE
Recommended Quest is not displayed for some Items

### ISSUE THREAD

**Issue by Donnie-B** [Expugn/priconne-quest-helper#37]
**Describe the bug**
The recommended quest for some equipment is not displayed

**To Reproduce**
1. Try to display recommended quest for Godly Red Ring - Ruby Rose or other red frame accessories (Popcorn Necklace, etc)
2. Requested Items and Ingredients are displayed just fine but the recommended quests is empty

**Expected behavior**
Recommended quest for all items should be displayed properly.

**Screenshots**
![2021-02-15_21-52-50](https://user-images.githubusercontent.com/12907691/107955132-6307b280-6fd8-11eb-885f-0c8c97ddaa85.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Firefox
 - Version 78.7.1esr

**Comment by Expugn** [comment]
Google Chrome v88.0.4324
![image](https://user-images.githubusercontent.com/5342885/107980235-bfd18180-6f74-11eb-81c7-5447fd1bdf36.png)
Firefox 85.0.2
![image](https://user-images.githubusercontent.com/5342885/107979984-56517300-6f74-11eb-8934-ce56dddb2a23.png)

I don't seem to have and can't reproduce the issue on Google Chrome and Firefox.

Is it an issue with your settings? I am currently using the default settings:
![image](https://user-images.githubusercontent.com/5342885/107980392-03c48680-6f75-11eb-9fc2-a2a4d0d94f8a.png)

Make sure the red bordered item under `Ignore Item Rarity in Recipe` isn't disabled and that `Lowest Quest Chapter Displayed`/`Highest Quest Chapter Displayed` is set to a range of chapters that actually have the items.

**Comment by Donnie-B** [comment]
Seems like I missed the Highest Quest Chapter setting.

Now that I have ticked the Max checkbox, the quests are displayed properly.

Thanks for the reply.
