### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by TYUUKUN** [Expugn/priconne-quest-helper#41]
Hello, it's wonderful site.
pls, can you add tags about this?

![EgssFQtWkAQ0ige](https://user-images.githubusercontent.com/87311468/125282280-1c13b400-e30f-11eb-9682-aa0e436b8ca9.jpg)

**Comment by Expugn** [comment]
Hi,
Can you clarify what you mean by "tags" and what you're referring to when you say "this"? My item list doesn't look like your screenshot.

![Screenshot_20210712-080045_PrincessConnectRedive](https://user-images.githubusercontent.com/5342885/125310480-7862dd80-e2e7-11eb-8589-abb3ee42e9b2.jpg)

**Comment by Expugn** [comment]
Closed due to lack of response.
