### ISSUE TITLE
Can't Export Data

### ISSUE THREAD

**Issue by Phoblaz** [Expugn/priconne-quest-helper#42]
I can't generate URL for export save data when i use google chrome
It stuck in this display
In safari it haven't this problem. 

![S__16539654](https://user-images.githubusercontent.com/90124741/132116129-de2c7cee-4b63-4a0f-95c8-040d674e2e7e.jpg)

 - Device: iPad Pro 11 2021
 - OS: iOS14.7.1
 - Browser google chrome
 - Version 93.0.4577.39

**Comment by Expugn** [comment]
Tested on `Windows10 using Chrome 92.0.4515.159` and `Android10 using Chrome 93.0.4577.62` and I can't seem to replicate the issue.

Both devices are exporting `Projects` and `Settings` while a "Djeeta [1 - 13]" preset project is saved.

I'll look into it more, but I can't guarantee a fix for this issue without any leads.

EDIT (October 10, 2021): Closing this issue until more details can be found.
