### ISSUE TITLE
Global Map 22 equipment doesn't match either legacy recipe

### ISSUE THREAD

**Issue by alsnpk** [Expugn/priconne-quest-helper#44]
(First of all, thank you for the great site!)

**Describe the bug**
The new equipment recently added on global for map 22 doesn't line up exactly with either "Legacy Equipment Data (Before 2019.08.31)" or "Legacy Equipment Data 2 (Before 2022.02.28)".
It seems like a mix of both.

The main ingredient matches the Legacy 2 data, but the sub-ingredients match the Legacy 1 data. 

Older equipment on global still matches Legacy 1, as far as I can tell. 

**To Reproduce**
1. Go to either the recipe screen or prepare to add a new item in quest helper.
2. Select any new equipment added for map 22.
3. Reference either legacy setting vs. the in-game recipe.

**Expected behavior**
The equipment recipe should either match one of the Legacy options, or might need a different option.
(Obviously it wouldn't work if it were to match a different Legacy option than the rest of the global equipment.)

**Screenshots**
Legacy 1 & 2 recipes for Arbiter's Greatsword
![Screenshot_20220302-140251336 (1).png](https://user-images.githubusercontent.com/100779463/156379913-f7e6349a-7ad3-4a2e-8dd7-341d1f9761bb.png)
Sub-ingredients line up with Legacy 1, but main ingredient needs 20, not 25
![Screenshot_20220302-140343979 (1).png](https://user-images.githubusercontent.com/100779463/156379998-504de61d-0c88-4538-b81c-da35bba949ba.png)

**Comment by Expugn** [comment]
Welp, didn't realize CrunchyRoll would do something like this.
I'll probably just give up and add a specific equipment/character data file for different servers.

May take some time to implement, but thank you for the report!

**Comment by Expugn** [comment]
You can now select specifically the English server as well as other game regions.
![image](https://user-images.githubusercontent.com/5342885/156492533-217fe07b-481d-409e-8d67-3bc30ebc018f.png)

There *may* be issues since there were a lot of changes, but hopefully this is better than figuring out what Legacy version to choose.

**Comment by alsnpk** [comment]
That's awesome, thank you very much! 👍
