### ISSUE TITLE
Equipment not showing correctly when switching data region

### ISSUE THREAD

**Issue by DeinAlptraum** [Expugn/priconne-quest-helper#45]
**Describe the bug**
Changing the "Equipment Data Type" setting from Japan Server to English Server seems to break the data of an existing project. When loading the next time on a new tab, some pieces of equipment won't show under the "Requested Items" section and are also apparently ignored in the "Recommended Quests" section. See screenshot below for example.

**To Reproduce**
1. Open the quest helper in a new tab (I tested in incognito), verify that the equipment data setting is set to Japan Server
2. Add one each of items "Lightning Blade" and "Empress Robe" to the selection (purple rarity, Lightning Blade should be first item in that section, Empress Robe is a purple-colored robe for mages, see screenshot at the bottom)
3. Save as new project.
4. Change equipment data to English server and save settings. Equipment/fragment quantities update correctly.
5. Open the quest helper again in new tab. Verify that equipment data is still set to English Server
6. Load the project created in step 3
7. Notice how only Lightning Blade shows up in the required items section and the recommended quests are based off this. Empress Robe does not show up, despite being still properly set to 1 needed. Changing the amount has no effect.

**Expected behavior**
After switching the equipment data region, equipment should still show up as before, just quantities should change.

**Screenshots**
Screenshot shows Lightning Blade and Empress Robe each selected once, but only Lightning Blade showing up under required items. This happens after switching equipment data from Japanese to English
![image](https://user-images.githubusercontent.com/51118500/156935771-2f508d59-5e6c-4054-96de-f809678b3b94.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux on KDE
 - Browser: Firefox
 - Version: 97.0.2-1

**Additional context**
The problem seems to disappear by setting the equipment data to Japanese, and then to English again. However, that only works for the current tab, i.e. if opened in a new tab or current tab is reloaded, the problem reappears.
After a bit of testing, it seems that purple rarity weapons all show up correctly, but none of the purple rarity armors/shields/necklaces/pendants/etc. show up correctly.

**Comment by Expugn** [comment]
The issue should now be resolved as of <https://github.com/Expugn/priconne-quest-helper/commit/9a45184e943edc21fc385708e0f276a75b033815>

The reason of this issue was because I was lazy and forgot to update rarity IDs when creating regional equipment data, lol.

Thanks for the report, and sorry for the delayed response! Please let me know if further issues arise.
