### ISSUE TITLE
[Bug Report] "Delete Project" button can delete "[All Projects...]"

### ISSUE THREAD

**Issue by tonyjphan** [Expugn/priconne-quest-helper#47]
Hi Expugn! The [partial project completion feature](https://github.com/Expugn/priconne-quest-helper/issues/46) you implemented a few months back was a huge quality of life boost and I find myself using it almost exclusively over the original project completion method :) 

**Describe the bug**
I haven't found any other bugs with the partial project completion feature, but I noticed recently that if you click `Delete Project` with `[All Projects...]` as the selected saved project, it will delete all your projects with no warning as it seems to be treated similarly to other projects. It's possible that this may have begun around the time the partial project completion feature was added, but I'm not entirely sure.

**To Reproduce**
Steps to reproduce the behavior (tested on a separate browser instance):
1. Create a few projects
2. Change `Selected Saved Project` to `[All Projects...]`
3. Click `Delete Project`
4. All projects are deleted

**Expected behavior**
If this is a bug, it would be great if the `Delete Project` button could be disabled if `[All Projects...]` is the currently selected project, regardless of whether it has been loaded.

If this is not a bug, it would be great to get something similar to a warning/"are you sure" confirmation to ensure that the user wanted to delete everything, as it's possible to misclick `Delete Project` due to its proximity to `Complete Project`.

**Screenshots**
Clicking `Delete Project` with `[All Projects...]` selected removes all projects from the saved project list and displays a notification confirming that it was deleted:
![all_projects_deleted](https://user-images.githubusercontent.com/12322401/197372548-58e4bfc1-f931-42df-b3f5-1a799e3a332c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Firefox/Chrome
 - Version: `Last Quest Update: October 15, 2022`

**Additional context**
N/A

**Comment by Expugn** [comment]
Hi,

Yes, this behavior of deleting all projects when `[All Projects...]` is selected is intended. I've since added the confirmation alert as suggested here: <https://github.com/Expugn/priconne-quest-helper/commit/c1848acb948498200d81e280650284d3859cadf7>

Thanks for your feedback!

**Comment by tonyjphan** [comment]
This is what I was looking for, thank you :) appreciate the quick response/action!
